# Generated by Django 5.0.7 on 2024-07-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='contracts/')),
                ('text', models.TextField()),
                ('entities', models.TextField()),
                ('highlighted_text', models.TextField()),
                ('predicted_text', models.TextField()),
                ('summarized_text', models.TextField()),
            ],
        ),
    ]
